return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  config = function()
    local wk = require("which-key")
    wk.setup({
      preset = "modern",
      delay = 150,
      notify = false,
      filter = function(mapping)
        local description = mapping.desc or mapping.group or ""
        return description:find("[\128-\255]") ~= nil
      end,
      plugins = {
        presets = {
          operators = false,
          motions = false,
          text_objects = false,
          windows = false,
          nav = false,
          z = false,
          g = false,
        },
      },
      win = { border = "rounded", padding = { 1, 1 } },
    })

    wk.add({
      { "<leader>b", group = "缓冲区" },
      { "<leader>c", group = "代码" },
      { "<leader>d", group = "调试" },
      { "<leader>f", group = "查找" },
      { "<leader>g", group = "版本控制" },
      { "<leader>h", group = "文件标记" },
      { "<leader>m", group = "构建" },
      { "<leader>o", group = "任务" },
      { "<leader>r", group = "Rust 开发" },
      { "<leader>s", group = "窗口" },
      { "<leader>t", group = "测试" },
      { "<leader>u", group = "开关" },
      { "<leader>x", group = "诊断" },

      { "g", group = "代码导航与移动" },
      { "gg", desc = "跳到文件开头" },
      { "gd", desc = "跳转定义" },
      { "gD", desc = "跳转声明" },
      { "gr", desc = "查找引用" },
      { "gi", desc = "跳转实现" },
      { "gy", desc = "跳转类型定义" },
      { "gv", desc = "重新选择上次选区" },
      { "gq", desc = "格式化文本" },
      { "gt", desc = "下一个标签页" },
      { "gT", desc = "上一个标签页" },
      { "z", group = "代码折叠" },
      { "zR", desc = "展开全部折叠" },
      { "zM", desc = "关闭全部折叠" },
      { "za", desc = "切换当前折叠" },
      { "zc", desc = "关闭当前折叠" },
      { "zo", desc = "展开当前折叠" },
      { "[", group = "跳到上一个" },
      { "]", group = "跳到下一个" },
      { "[b", desc = "上一个缓冲区" },
      { "]b", desc = "下一个缓冲区" },
      { "[d", desc = "上一条诊断" },
      { "]d", desc = "下一条诊断" },
      { "[h", desc = "上一处修改" },
      { "]h", desc = "下一处修改" },
      { "[t", desc = "上一个标签页" },
      { "]t", desc = "下一个标签页" },
      { "<C-w>", group = "窗口操作" },
      { "<C-w>h", desc = "切到左侧窗口" },
      { "<C-w>j", desc = "切到下方窗口" },
      { "<C-w>k", desc = "切到上方窗口" },
      { "<C-w>l", desc = "切到右侧窗口" },
      { "<C-w>v", desc = "左右分屏" },
      { "<C-w>s", desc = "上下分屏" },
      { "<C-w>c", desc = "关闭当前窗口" },
      { "<C-w>o", desc = "只保留当前窗口" },
    })
  end,
}
