return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  config = function()
    local wk = require("which-key")
    wk.setup({
      preset = "modern",
      delay = 150,
      notify = false,
      filter = function(mapping)
        local description = mapping.desc or mapping.group or ""
        return description:find("[\128-\255]") ~= nil
      end,
      plugins = {
        presets = {
          operators = false,
          motions = false,
          text_objects = false,
          windows = false,
          nav = false,
          z = false,
          g = false,
        },
      },
      win = { border = "rounded", padding = { 1, 1 } },
    })

    wk.add({
      { "<leader>b", group = "缓冲区" },
      { "<leader>c", group = "代码" },
      { "<leader>d", group = "调试" },
      { "<leader>f", group = "查找" },
      { "<leader>g", group = "版本控制" },
      { "<leader>h", group = "文件标记" },
      { "<leader>m", group = "构建" },
      { "<leader>o", group = "任务" },
      { "<leader>r", group = "运行 / Rust 开发" },
      { "<leader>s", group = "窗口" },
      { "<leader>t", group = "测试 / 终端" },
      { "<leader>T", group = "标签页" },
      { "<leader>u", group = "开关" },
      { "<leader>x", group = "诊断" },

      { "g", group = "代码导航与移动" },
      { "gg", desc = "跳到文件开头" },
      { "gd", desc = "跳转定义" },
      { "gD", desc = "跳转声明" },
      { "gr", desc = "查找引用" },
      { "gi", desc = "跳转实现" },
      { "gy", desc = "跳转类型定义" },
      { "gv", desc = "重新选择上次选区" },
      { "gq", desc = "格式化文本" },
      { "gc", desc = "注释切换（内置）" },
      { "gs", group = "环绕操作" },
      { "gsa", desc = "添加环绕" },
      { "gsd", desc = "删除环绕" },
      { "gsr", desc = "替换环绕" },
      { "gsh", desc = "高亮环绕" },
      { "z", group = "代码折叠" },
      { "zR", desc = "展开全部折叠" },
      { "zM", desc = "关闭全部折叠" },
      { "za", desc = "切换当前折叠" },
      { "zc", desc = "关闭当前折叠" },
      { "zo", desc = "展开当前折叠" },
      { "[", group = "跳到上一个" },
      { "]", group = "跳到下一个" },
      { "[d", desc = "上一条诊断" },
      { "]d", desc = "下一条诊断" },
      { "[h", desc = "上一处修改" },
      { "]h", desc = "下一处修改" },
      { "<S-Left>", desc = "上一个缓冲区" },
      { "<S-Right>", desc = "下一个缓冲区" },
      { "<S-Up>", desc = "上一个标签页" },
      { "<S-Down>", desc = "下一个标签页" },
      { "<C-i>", desc = "切到上方窗口" },
      { "<C-j>", desc = "切到左侧窗口" },
      { "<C-k>", desc = "切到下方窗口" },
      { "<C-l>", desc = "切到右侧窗口" },
      { "<C-PageUp>", desc = "缩小窗口宽度" },
      { "<C-PageDown>", desc = "扩大窗口宽度" },
      { "<C-S-PageUp>", desc = "缩小窗口高度" },
      { "<C-S-PageDown>", desc = "扩大窗口高度" },
    })
  end,
}
